version: '1.0'
name: pipeline-20220514
displayName: pipeline-20220514
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-1e09ddc9
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor:
      - mgang
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - yarn build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - docs/.vuepress/dist
permissions:
  - role: admin
    members:
      - mgang
